### PR TITLE
Tsolverhandler cleanup

### LINKED ISSUE #556: MacOS 12.5 / apple silicone: Regression errors on `regression/QF_AX` on master
When running on the above mentioned system, for some reason almost all regression tests in `regression/QF_AX/` (except `QF_AX/trivially_unsat.smt2` and `QF_AX/swap_trivial_unsat.smt2`) fail on an `assert` (the Release binary crashes).  Quickly looking they all seem to have the same stack trace (below).  I don't know why this is.  I didn't notice anything strange on the other regression tests.

These errors do not show up obviously on the systems we test in CI.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #0: 0x0000000195662d98 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x0000000195697ee0 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x00000001955d2340 libsystem_c.dylib`abort + 168
    frame #3: 0x00000001955d1754 libsystem_c.dylib`__assert_rtn + 272
  * frame #4: 0x0000000100f2a584 opensmt`Map<PTRef, ERef, PTRefHash, Equal<PTRef>>::operator[](this=0x0000000106603ab0, k=0x000000016fdf8750) const at Map.h:120:9
    frame #5: 0x0000000100f29e88 opensmt`EnodeStore::getERef(this=0x0000000106603a38, tr=(x = 52)) const at EnodeStore.h:104:55
    frame #6: 0x0000000100edc8e4 opensmt`Egraph::termToERef(this=0x0000000106603880, p=(x = 52)) const at Egraph.h:241:57
    frame #7: 0x0000000100ee8efc opensmt`ArraySolver::declareAtom(this=0x000000016fdf9850, term=(x = 52))::TermCollectorConfig::visit(PTRef) at ArraySolver.cc:142:36
    frame #8: 0x0000000100eb1dac opensmt`TermVisitor<ArraySolver::declareAtom(PTRef)::TermCollectorConfig>::visit(this=0x000000016fdf98a0, root=(x = 80)) at TreeOps.h:67:17
    frame #9: 0x0000000100eaf3b4 opensmt`ArraySolver::declareAtom(this=0x0000000106203680, tr=(x = 80)) at ArraySolver.cc:155:53
    frame #10: 0x00000001009ee278 opensmt`TSolverHandler::declareAtom(this=0x0000000106503358, tr=(x = 80)) at TSolverHandler.cc:57:26
    frame #11: 0x00000001009c855c opensmt`THandler::declareAtom(this=0x0000000105d00800, tr=(x = 80)) at THandler.cc:453:24
    frame #12: 0x0000000100350420 opensmt`CoreSMTSolver::declareVarsToTheories(this=0x0000000108203680) at CoreSMTSolver.cc:1662:32
    frame #13: 0x00000001003525d8 opensmt`CoreSMTSolver::solve_(this=0x0000000108203680) at CoreSMTSolver.cc:1705:5
    frame #14: 0x00000001002b3b1c opensmt`SimpSMTSolver::solve_(this=0x0000000108203680, do_simp=false, turn_off_simp=true) at SimpSMTSolver.cc:164:18
    frame #15: 0x0000000100fc8e6c opensmt`SimpSMTSolver::solve(this=0x0000000108203680, assumps=0x000000016fdfb510, do_simp=false, turn_off_simp=true) at SimpSMTSolver.h:204:50
    frame #16: 0x0000000100fc84b0 opensmt`Cnfizer::solve(this=0x0000000106203a70, en_frames=0x000000016fdfbcd0) at Cnfizer.cc:105:19
    frame #17: 0x0000000100087980 opensmt`MainSolver::solve_(this=0x0000000106203980, enabledFrames=0x000000016fdfbcd0) at MainSolver.h:132:19
    frame #18: 0x00000001000831ec opensmt`MainSolver::solve(this=0x0000000106203980) at MainSolver.cc:306:20
    frame #19: 0x00000001000816e4 opensmt`MainSolver::check(this=0x0000000106203980) at MainSolver.cc:282:20
    frame #20: 0x0000000100172f78 opensmt`Interpret::checkSat(this=0x000000016fdfee00) at Interpret.cc:569:24
    frame #21: 0x000000010014ea7c opensmt`Interpret::interp(this=0x000000016fdfee00, n=0x0000000105e04390) at Interpret.cc:269:21
    frame #22: 0x0000000100184a9c opensmt`Interpret::execute(this=0x000000016fdfee00, r=0x0000000105e04360) at Interpret.cc:1047:9
    frame #23: 0x0000000100185018 opensmt`Interpret::interpFile(this=0x000000016fdfee00, in=0x00000001ee5f0d10) at Interpret.cc:1060:5
    frame #24: 0x000000010000820c opensmt`main(argc=2, argv=0x000000016fdff600) at opensmt.cc:157:29
    frame #25: 0x000000010327d08c dyld`start + 520
```

### PR DESCRIPTION
**Pull request by aehyvari**
Currently the order dictated in which solvers should be accessed, e.g., when asserting literals, is defined in a vector `TSolverHandler::SolverSchedule`.  However, the code does not respect this order.  Instead the code uses an order that is non-deterministic between systems as it depends on in which order certain static data structures are initialised.

This commit fixes the code to follow strictly the order from `TSolverHandler::SolverSchedule`.  As a result of the cleanup, we get rid of an extra data structure in `TSolverHandler` that was used to store the solvers based on their IDs.

Fixes #556.

### CODE REVIEW

File: src/tsolvers/THandler.cc [hunk 1]
```diff
@@ -120,14 +119,15 @@ void THandler::getConflict (
...
-        int i;
-        for (i = 0; i < getSolverHandler().tsolvers.size(); i++) {
-            if (getSolverHandler().tsolvers[i] != nullptr && getSolverHandler().tsolvers[i]->hasExplanation()) {
-                getSolverHandler().tsolvers[i]->getConflict(explanation);
-                break;
+        bool found;
+        for (auto solver : getSolverHandler().solverSchedule) {
+            if (solver->hasExplanation()) {
+                solver->getConflict(explanation);
+                found = true;
```
Comment (blishko) [inline src/tsolvers/THandler.cc:126]: I think we should keep the `break` here, no?

**Review by blishko — COMMENTED** [review]
Nice! I think this should work.

File: src/tsolvers/THandler.cc (hunk 1 above)
Comment (aehyvari) [reply src/tsolvers/THandler.cc:126]: True, no need to remove it.  I also seem to have forgotten to initialize `found`, fixed in the commit below.

**Review by blishko — APPROVED** [review]
LGTM!
