### PR TITLE
Bringing examples up to date and integrating them into CI

### LINKED ISSUE #24: Examples are not compiling
Hello @aehyvari @blishko following up from my email. I am still have the issue.

I compiled successfully and installed with `sudo make install`. I am working on Ubuntu.
However [examples](https://github.com/usi-verification-and-security/opensmt/tree/master/examples) are not compiling.
Probably not all of the examples, but I run the [make file ](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/Makefile) which is compiling [test_itp.cc](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test_itp.cc). I also tried to directly compile [test.cc](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test.cc)

Here is my error:
image

Also tried [test_c.c](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test_c.c)

and got this : 
image

Thank you

### PR DESCRIPTION
**Pull request by blishko**
- Updated examples so that they can be compiled with current source code version; Fixed #24 
- Integrated examples into CI to test building external applications with OpenSMT library
- Fixed incorrect include that prevented compilation of external applications using OpenSMT library

### CODE REVIEW

File: examples/test_itp.cc [hunk 1]
```diff
@@ -83,6 +74,7 @@ main(int argc, char** argv)
         vector<PTRef> itps;
         solver.getSingleInterpolant(itps, mask);
         cerr << ";Interpolant:\n;" << logic.printTerm(itps[0]) << endl;
+#endif // PRODUCE_PROOF
     }
     else if (r == s_Undef)
         printf("unknowon\n");
```
Comment (aehyvari) [inline examples/test_itp.cc]: unknown :)

Comment (blishko) [reply examples/test_itp.cc]: fixed :)
