### PR TITLE
Fix crash in UF interpolator

### LINKED ISSUE #231: Bug in the EUF interpolation
When running UpProver in EUF encoding for the attached example, an exception is thrown in `getSingleInterpolant(interpolants, mask)`. 

Up to OpenSMT version 555c592f the verification was successful, but it seems after d1592f50 onwards verification of the example crashes.

- Example: see [here](https://gist.github.com/sepideha/a803d4497288b54cfd538cfa2ce6f83a)

- Exact command line resulting in the issue: run in UpProver (4cf51de8 or any older version): `./upprover --logic qfuf --bootstrapping ex7-v5.c`

- What behaviour did you expect: UNSAT in EUF with generated interpolants

- What happened instead: exception thrown in `getSingleInterpolant(interpolants, mask)` with message `libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found`

P.S. I also tried OpenSMT ec7cf31c but the following exception is thrown in the same method `libc++abi.dylib: terminating with uncaught exception of type OsmtInternalException: No color detected for term`

### PR DESCRIPTION
**Pull request by blishko**
Because we re-use one theory solver for all theory conflicts, it may happen that the explanation of a conflict depends on a term not present in that particular conflict (but is present in the input formula).
This breaks the invariant assumed before, i.e., that local coloring information is enough to color the `CGraph` (congruence graph representing the explanation).
But even in global coloring information, a term (like `f(x)`) can originally be assigned only color `A` (when present only in partition `A`) while in the `CGraph` we need to color it as `AB` because both `f` and `x` have color `AB`.
This required a small change in the code which was not prepared for such situation.

Added are a regression and a unit test that show this problem, although they are sensitive to the order in which the terms are introduced.

Fixes #231.

### CODE REVIEW

File: src/tsolvers/egraph/UFInterpolator.cc [hunk 1]
```diff
@@ -342,16 +295,32 @@ bool UFInterpolator::colorEdgesFrom(CNode * x) {
...
 
+void UFInterpolator::colorCongruenceEdge(CEdge * edge) {
+    assert(edge);
+    CNode * from = edge->source;
+    CNode * to = edge->target;
+    if (from->color == to->color) {
+        assert (from->color);
+        edge->color = from->color == I_AB ? resolveABColor() : from->color;
+    } else { // Different colors: choose intersection
+        // It is not possible that are incompatible
```
Comment (aehyvari) [inline src/tsolvers/egraph/UFInterpolator.cc:306]: the *colors* are incompatible?

Comment (blishko) [reply src/tsolvers/egraph/UFInterpolator.cc]: Updated.

File: src/tsolvers/egraph/UFInterpolator.cc [hunk 2]
```diff
@@ -1264,3 +1233,50 @@ bool UFInterpolator::checkColors() {
...
+    cgraph.addCEdge(from, intermediate, PTRef_Undef);
+    assert(from->next != nullptr); // the added edge is from->next
+    assert(from->next->target == intermediate);
+    // Choose a color; we know that intermediate is AB, so we color edge based on from
+    assert (from->color == I_A || from->color == I_B || from->color == I_AB);
+    from->next->color = from->color == I_AB ? resolveABColor() : from->color;
+
+    cgraph.addCEdge(intermediate, to, PTRef_Undef);
+//    intermediate->next->color = to->color;
+    if (intermediate_next != nullptr) {
```
Comment (aehyvari) [inline src/tsolvers/egraph/UFInterpolator.cc:1272]:
```suggestion
    if (intermediate_next) {
```

File: src/tsolvers/egraph/UFInterpolator.cc [hunk 3]
```diff
@@ -1264,3 +1233,50 @@ bool UFInterpolator::checkColors() {
...
+    CNode * from = edge->source;
+    CNode * to = edge->target;
+    assert (from->next->target == to);
+    // Adds corresponding node
+    CNode * intermediate = nullptr;
+    CNode * intermediate_next = nullptr;
+    PTRef intermediate_next_reason = PTRef_Undef;
+    if (cgraph.hasNode(intermediateTerm)) {
+        intermediate = cgraph.getNode(intermediateTerm);
+        if (intermediate->next != nullptr) {
```
Comment (aehyvari) [inline src/tsolvers/egraph/UFInterpolator.cc:1248]:
```suggestion
        if (intermediate->next) {
```

**Review by aehyvari — APPROVED** [review]
Looks good to me.  I left two small suggestions.  While going through the PR I was cleaning some code you didn't touch.  Should I commit them to this PR or make a separate one?  They're minor but in my opinion improve readability.

File: src/tsolvers/egraph/UFInterpolator.cc (hunk 3 above)
Comment (blishko) [reply src/tsolvers/egraph/UFInterpolator.cc:1248]: Looks good!

**Comment by blishko** [comment]
Let me rebase this, then you can commit your changes and then we can merge.

**Comment by aehyvari** [comment]
OK I committed my cleanup.
