### PR TITLE
Fix mod corner cases

### LINKED ISSUE #628: Unsoundness in `div` & `mod` when divisor is 1 or -1
Opensmt computes incorrectly `(div x 1)`, `(mod x 1)`, `(div x -1)`, and `(mod x -1)`.

### PR DESCRIPTION
**Pull request by aehyvari**
OpenSMT computes incorrectly `(mod x 1)`, `(mod x -1)`, `(div x 1)` and
`(div x -1)` because the special handling for these is missing.  This
PR adds the simplifications directly to `ArithLogic`.

There's also unit tests for the above cases. 

Fixes #628

### CODE REVIEW

File: test/unit/test_LIALogicMkTerms.cc [hunk 1]
```diff
@@ -118,6 +128,16 @@ TEST_F(LIALogicMkTermsTest, testDiv_Constants_NegNeg) {
     EXPECT_EQ(mod, logic.getTerm_IntOne());
 }
 
+TEST_F(LIALogicMkTermsTest, testDiv_One) {
+    PTRef one = logic.getTerm_IntOne();
+    PTRef mod = logic.mkIntDiv(x, one);
+    EXPECT_EQ(mod, x);
+    PTRef minusOne = logic.getTerm_IntMinusOne();
+    mod = logic.mkIntDiv(x, minusOne);
+    EXPECT_EQ(mod, logic.mkNeg(x));
```
Comment (blishko) [inline test/unit/test_LIALogicMkTerms.cc:137]:
```suggestion
    PTRef div = logic.mkIntDiv(x, one);
    EXPECT_EQ(div, x);
    PTRef minusOne = logic.getTerm_IntMinusOne();
    div = logic.mkIntDiv(x, minusOne);
    EXPECT_EQ(div, logic.mkNeg(x));
```

**Review by blishko — APPROVED** [review]
LGTM!
